# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Zip Folder
        run: zip -r repo.zip . # -x ".git/*" ".github/*"

      - name: Copy single file to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: repo.zip
          remote: /var/www/vhosts/bitfertig.de/tools.bitfertig.de/${{ github.run_id }}.zip
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}

      # SSH connect
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          script: |
            cd /var/www/vhosts/bitfertig.de/tools.bitfertig.de/
            unzip ${{ github.run_id }}.zip -o -f
            rm ${{ github.run_id }}.zip
      
      #- name: FTP-Deploy-Action
      #  uses: SamKirkland/FTP-Deploy-Action@3.1.1
      #  with:
      #    ftp-server: ${{ secrets.FTP_SERVER }}/tools.bitfertig.de/
      #    ftp-username: ${{ secrets.FTP_USERNAME }}
      #    ftp-password: ${{ secrets.FTP_PASSWORD }}
      
      - name: curl
        uses: wei/curl@master
        with:
          args: https://tools.bitfertig.de/worker.php
